# =========================================================
# API Gateway
# =========================================================

server.port=8088

spring.application.name=api-gateway
app.cors.allowed-origin-patterns=http://localhost:4200
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_UNIQUE


# =========================================================
# Property Service - 8082
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=property-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://172.27.212.27:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/property/**

spring.cloud.gateway.server.webflux.routes[1].id=property-service-inventory-sync
spring.cloud.gateway.server.webflux.routes[1].uri=http://172.27.212.27:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/internal/inventory-sync/**

spring.cloud.gateway.server.webflux.routes[2].id=property-service-uploads
spring.cloud.gateway.server.webflux.routes[2].uri=http://172.27.212.27:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/uploads/**

# =========================================================
# Policy Management - 8083
# =========================================================

spring.cloud.gateway.server.webflux.routes[3].id=policy-management-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://172.27.212.27:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/policies/**


# =========================================================
# Auth Service - 8084
# =========================================================

spring.cloud.gateway.server.webflux.routes[4].id=pms-auth
spring.cloud.gateway.server.webflux.routes[4].uri=http://172.27.212.27:8084
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/v1/auth/**


# =========================================================
# Housekeeping - 8086
# =========================================================

spring.cloud.gateway.server.webflux.routes[5].id=housekeeping-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://172.27.212.27:8086
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/v1/housekeeping/**


spring.cloud.gateway.server.webflux.routes[6].id=housekeeping-service-room-master
spring.cloud.gateway.server.webflux.routes[6].uri=http://172.27.212.27:8086
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/v1/housekeeping/room-master/**

# =========================================================
# Rate Management - 8087
# =========================================================

spring.cloud.gateway.server.webflux.routes[7].id=rate-management-service
spring.cloud.gateway.server.webflux.routes[7].uri=http://172.27.212.27:8087
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/master-rooms/**

spring.cloud.gateway.server.webflux.routes[8].id=rate-management-service
spring.cloud.gateway.server.webflux.routes[8].uri=http://172.27.212.27:8087
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/rate-plans/**

# =========================================================
# PMS-Reservation - 8090
# =========================================================

spring.cloud.gateway.server.webflux.routes[9].id=PMS-Reservation-service
spring.cloud.gateway.server.webflux.routes[9].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/v1/frontdesk/**

spring.cloud.gateway.server.webflux.routes[10].id=PMS-Reservation-Guest-Lisitng
spring.cloud.gateway.server.webflux.routes[10].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/v1/guest-listing/**

spring.cloud.gateway.server.webflux.routes[11].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[11].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/v1/housekeeping/rooms/**

spring.cloud.gateway.server.webflux.routes[12].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[12].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/v1/reservations/**

spring.cloud.gateway.server.webflux.routes[13].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[13].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/v1/reservations/bookings/{confirmationNumber}/check-in/**

spring.cloud.gateway.server.webflux.routes[14].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[14].uri=http://172.27.212.27:8090
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/api/v1/reservations/bookings/{confirmationNumber}/check-out/**



# =========================================================
# Folio Billing - 8080
# =========================================================

spring.cloud.gateway.server.webflux.routes[15].id=folio-billing-service
spring.cloud.gateway.server.webflux.routes[15].uri=http://172.27.212.27:8080
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/api/v1/billingFolio/**

