server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: property-service
          uri: lb://property-service
          order: 1
          predicates:
            - Path=/api/properties/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/