# =========================================================
# API Gateway
# =========================================================

server.port=8088

spring.application.name=api-gateway
app.cors.allowed-origin-patterns=${APP_CORS_ALLOWED_ORIGIN_PATTERNS:http://localhost:4200}
spring.cloud.gateway.server.webflux.default-filters[0]=DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials Access-Control-Allow-Methods Access-Control-Allow-Headers RETAIN_UNIQUE


# =========================================================
# Property Service - 8082
# =========================================================

API_BASE_URL = http://localhost


spring.cloud.gateway.server.webflux.routes[0].id=property-service
spring.cloud.gateway.server.webflux.routes[0].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/property/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[1].id=property-service-inventory-sync
spring.cloud.gateway.server.webflux.routes[1].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/V1/internal/inventory-sync/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[2].id=property-service-uploads
spring.cloud.gateway.server.webflux.routes[2].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/uploads/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=2


spring.cloud.gateway.server.webflux.routes[3].id=property-service-content
spring.cloud.gateway.server.webflux.routes[3].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/content/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[4].id=property-service-finance
spring.cloud.gateway.server.webflux.routes[4].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/finance/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=2
    
spring.cloud.gateway.server.webflux.routes[5].id=property-service-payments
spring.cloud.gateway.server.webflux.routes[5].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/payments/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[6].id=property-service-rooms
spring.cloud.gateway.server.webflux.routes[6].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/rooms/**
spring.cloud.gateway.server.webflux.routes[6].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[7].id=property-service-taxes
spring.cloud.gateway.server.webflux.routes[7].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/taxes/**
spring.cloud.gateway.server.webflux.routes[7].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[8].id=property-service-drafts
spring.cloud.gateway.server.webflux.routes[8].uri=${API_BASE_URL}:8082
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/property/drafts/**
spring.cloud.gateway.server.webflux.routes[8].filters[0]=StripPrefix=2

# =========================================================
# Policy Management - 8083
# =========================================================

spring.cloud.gateway.server.webflux.routes[9].id=policy-management-service
spring.cloud.gateway.server.webflux.routes[9].uri=${API_BASE_URL}:8083
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/policies/**
spring.cloud.gateway.server.webflux.routes[9].filters[0]=StripPrefix=2


# =========================================================
# Auth Service - 8084
# =========================================================

spring.cloud.gateway.server.webflux.routes[10].id=pms-auth
spring.cloud.gateway.server.webflux.routes[10].uri=${API_BASE_URL}:8084
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/auth/**
spring.cloud.gateway.server.webflux.routes[10].filters[0]=StripPrefix=2


# =========================================================
# Housekeeping - 8086
# =========================================================

spring.cloud.gateway.server.webflux.routes[11].id=housekeeping-service
spring.cloud.gateway.server.webflux.routes[11].uri=${API_BASE_URL}:8086
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/housekeeping/**
spring.cloud.gateway.server.webflux.routes[11].filters[0]=StripPrefix=2


spring.cloud.gateway.server.webflux.routes[12].id=housekeeping-service-room-master
spring.cloud.gateway.server.webflux.routes[12].uri=${API_BASE_URL}:8086
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/housekeeping/room-master/**
spring.cloud.gateway.server.webflux.routes[12].filters[0]=StripPrefix=2

# =========================================================
# Rate Management - 8087
# =========================================================

spring.cloud.gateway.server.webflux.routes[13].id=rate-management-service
spring.cloud.gateway.server.webflux.routes[13].uri=${API_BASE_URL}:8087
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/master-rooms/**
spring.cloud.gateway.server.webflux.routes[13].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[14].id=rate-management-service
spring.cloud.gateway.server.webflux.routes[14].uri=${API_BASE_URL}:8087
spring.cloud.gateway.server.webflux.routes[14].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/rate-plans/**
spring.cloud.gateway.server.webflux.routes[14].filters[0]=StripPrefix=2

# =========================================================
# PMS-Reservation - 8090
# =========================================================

spring.cloud.gateway.server.webflux.routes[15].id=PMS-Reservation-service
spring.cloud.gateway.server.webflux.routes[15].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[15].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/frontdesk/**
spring.cloud.gateway.server.webflux.routes[15].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[16].id=PMS-Reservation-Guest-Lisitng
spring.cloud.gateway.server.webflux.routes[16].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[16].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/guest-listing/**
spring.cloud.gateway.server.webflux.routes[16].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[17].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[17].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[17].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/housekeeping/rooms/**
spring.cloud.gateway.server.webflux.routes[17].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[18].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[18].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[18].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/reservations/**
spring.cloud.gateway.server.webflux.routes[18].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[19].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[19].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[19].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/reservations/bookings/{confirmationNumber}/check-in/**
spring.cloud.gateway.server.webflux.routes[19].filters[0]=StripPrefix=2

spring.cloud.gateway.server.webflux.routes[20].id=PMS-Reservation-housekeeping-rooms
spring.cloud.gateway.server.webflux.routes[20].uri=${API_BASE_URL}:8090
spring.cloud.gateway.server.webflux.routes[20].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/reservations/bookings/{confirmationNumber}/check-out/**
spring.cloud.gateway.server.webflux.routes[20].filters[0]=StripPrefix=2



# =========================================================
# Folio Billing - 8080
# =========================================================

spring.cloud.gateway.server.webflux.routes[21].id=folio-billing-service
spring.cloud.gateway.server.webflux.routes[21].uri=${API_BASE_URL}:8080
spring.cloud.gateway.server.webflux.routes[21].predicates[0]=Path=/API-Gateway/PMS-FrontDesk/api/v1/billingFolio/**
spring.cloud.gateway.server.webflux.routes[21].filters[0]=StripPrefix=2

