ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS folio_code VARCHAR(30) NOT NULL DEFAULT 'A';

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS guest_name VARCHAR(160) NOT NULL DEFAULT '';

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS room_no VARCHAR(40) NOT NULL DEFAULT '';

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS total_charges NUMERIC(19,2) NOT NULL DEFAULT 0;

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS total_payment NUMERIC(19,2) NOT NULL DEFAULT 0;

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS outstanding_balance NUMERIC(19,2) NOT NULL DEFAULT 0;

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS last_updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE folio_db.folios
    ADD COLUMN IF NOT EXISTS transactions_json TEXT;

ALTER TABLE folio_db.folios
    ALTER COLUMN transactions_json TYPE TEXT;
