spring.application.name=pms-housekeeping
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/Property_Management_System_db?CurrentSchema=pms_housekeeping}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=pms_housekeeping


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.create-schemas=true
spring.flyway.schemas=pms_housekeeping
spring.flyway.default-schema=pms_housekeeping

server.port=${SERVER_PORT:8086}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
security.jwt.secret=${PMS_FRONTDESK_JWT_SECRET:pms-auth-super-secret-key-change-me-in-prod-2026}
housekeeping.window.horizon-days=${HOUSEKEEPING_WINDOW_HORIZON_DAYS:90}

