create table property_overview (
	id bigint generated by default as identity primary key,
	property_id varchar(36) not null unique,
	property_hero_image varchar(500) not null,
	property_description varchar(2000) not null,
	constraint fk_property_overview_property foreign key (property_id) references property(id)
);

create table guest_service_amenity (
	id bigint generated by default as identity primary key,
	property_id varchar(36) not null,
	section varchar(40) not null,
	code varchar(120) not null,
	enabled boolean not null,
	constraint fk_guest_service_amenity_property foreign key (property_id) references property(id)
);

create table nearby_location_accessibility (
	id bigint generated by default as identity primary key,
	property_id varchar(36) not null,
	section varchar(40) not null,
	location_type varchar(120) not null,
	location_name varchar(255) not null,
	distance_value double precision not null,
	distance_unit varchar(20) not null,
	travel_time_value integer not null,
	travel_time_unit varchar(20) not null,
	constraint fk_nearby_location_accessibility_property foreign key (property_id) references property(id)
);

create index idx_guest_service_amenity_property on guest_service_amenity(property_id);
create index idx_nearby_location_accessibility_property on nearby_location_accessibility(property_id);


