spring.application.name=Policy
server.port = 8083
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://172.27.57.*:*,https://172.27.57.*:*,https://172.27.212.*:*
security.jwt.secret=${PMS_FRONTDESK_JWT_SECRET:pms-auth-super-secret-key-change-me-in-prod-2026}
security.jwt.public-paths=/error,/swagger-ui/**,/v3/api-docs/**,/actuator/**,/uploads/**
security.jwt.public-paths=/error,/swagger-ui/**,/v3/api-docs/**,/actuator/**,/uploads/**
security.jwt.public-paths=/error,/swagger-ui/**,/v3/api-docs/**,/actuator/**,/uploads/**

property.service.url=http://localhost:8082/api/property/getPublishedProperty/{propertyId}
