spring.application.name=pms-auth
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5432/PMSystem_db?CurrentSchema=pms_auth
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=pms_auth
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000


spring.flyway.enabled=true
spring.flyway.validate-on-migrate=false
spring.flyway.create-schemas=true
spring.flyway.schemas=pms_auth
spring.flyway.default-schema=pms_auth

security.jwt.secret=${PMS_FRONTDESK_JWT_SECRET:pms-auth-super-secret-key-change-me-in-prod-2026}
security.jwt.access-token-expiration-seconds=600
security.jwt.refresh-token-expiration-seconds=1209600
security.jwt.public-paths=/error,/swagger-ui,/v3/api-docs,/actuator,/api/v1/auth/**
app.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,http://172.27.57.*:*,https://172.27.57.*:*

springdoc.api-docs.path= /v3/api-docs
swagger-ui.path= /swagger-ui.html

openapi.title=PMS Auth API
openapi.description=Authentication APIs for PMS
openapi.version=v1