server:
  port: 8085

spring:
  application:
    name: content-service
  datasource:
    url: jdbc:postgresql://localhost:5432/content_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: content
        hbm2ddl.create_namespaces: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

services:
  property-service:
    url: http://localhost:8081
