create table floor_property_area (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    floor_name varchar(120) not null,
    area_name varchar(150) not null,
    quantity integer not null,
    constraint fk_floor_property_area_property foreign key (property_id) references property(id)
);

create index idx_floor_property_area_property on floor_property_area(property_id);
create index idx_floor_property_area_floor on floor_property_area(property_id, floor_name);


