create table property_draft (
    id bigint generated by default as identity primary key,
    wizard_data text not null,
    schema_version integer not null,
    status varchar(32) not null,
    published_property_id varchar(36),
    version bigint,
    created_at timestamp not null,
    updated_at timestamp not null
);

create index idx_property_draft_status on property_draft(status);


