create table property (
    id bigint generated by default as identity primary key,
    title varchar(255) not null,
    address varchar(500) not null,
    city varchar(150) not null,
    country varchar(150) not null,
    created_at timestamp with time zone not null
);

create table room (
    id bigint generated by default as identity primary key,
    property_id bigint not null,
    name varchar(120) not null,
    count integer not null,
    constraint fk_room_property foreign key (property_id) references property(id)
);

create table tax (
    id bigint generated by default as identity primary key,
    property_id bigint not null unique,
    gst_number varchar(100) not null,
    tax_percentage double precision not null,
    constraint fk_tax_property foreign key (property_id) references property(id)
);

create table finance (
    id bigint generated by default as identity primary key,
    property_id bigint not null unique,
    currency varchar(10) not null,
    base_price double precision not null,
    constraint fk_finance_property foreign key (property_id) references property(id)
);

create table revenue (
    id bigint generated by default as identity primary key,
    property_id bigint not null unique,
    channel_manager_enabled boolean not null,
    commission_percentage double precision not null,
    constraint fk_revenue_property foreign key (property_id) references property(id)
);

