spring.application.name=property-service
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5432/pms_property_wizard
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.flyway.enabled=true

