-- Reference schema snapshot after applying migrations V1..V17.
-- This file is for documentation/ERD usage, not for Flyway execution.

create table property (
    id varchar(36) primary key,
    title varchar(255) not null,
    address varchar(500) not null,
    city varchar(150) not null,
    country varchar(150) not null,
    created_at timestamp not null,
    contact_name varchar(255) not null default '',
    contact_number varchar(64) not null default '',
    time_zone varchar(120) not null default '',
    night_audit_time varchar(10) not null default '',
    check_in_time varchar(10) not null default '',
    check_out_time varchar(10) not null default '',
    status varchar(32) not null default 'ACTIVE',
    created_by varchar(120) not null default 'system',
    property_code varchar(120) not null default '',
    property_type varchar(80) not null default '',
    total_no_of_rooms integer not null default 0,
    total_no_of_floors integer not null default 0,
    state varchar(150) not null default '',
    zip_code varchar(40) not null default '',
    website varchar(255) not null default ''
);

create table property_draft (
    id bigint generated by default as identity primary key,
    wizard_data text not null,
    schema_version integer not null,
    status varchar(32) not null,
    published_property_id varchar(36),
    version bigint,
    created_at timestamp not null,
    updated_at timestamp not null,
    lifecycle_state varchar(32) not null default 'DRAFT',
    current_step varchar(64) not null default 'PROPERTY_DETAILS',
    completed_steps varchar(500) not null default '',
    created_by varchar(120) not null default 'system',
    updated_by varchar(120) not null default 'system',
    published_by varchar(120)
);


create table property_overview (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null unique,
    property_hero_image varchar(500) not null,
    property_description varchar(2000) not null,
    constraint fk_property_overview_property foreign key (property_id) references property(id)
);

create table guest_service_amenity (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    section varchar(40) not null,
    code varchar(120) not null,
    enabled boolean not null,
    constraint fk_guest_service_amenity_property foreign key (property_id) references property(id)
);

create table nearby_location_accessibility (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    section varchar(40) not null,
    location_type varchar(120) not null,
    location_name varchar(255) not null,
    distance_value double precision not null,
    distance_unit varchar(20) not null,
    travel_time_value integer not null,
    travel_time_unit varchar(20) not null,
    constraint fk_nearby_location_accessibility_property foreign key (property_id) references property(id)
);

create table room_type (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    name varchar(120) not null,
    is_master boolean not null,
    master_room_name varchar(120),
    occupancy integer not null,
    constraint fk_room_type_property foreign key (property_id) references property(id)
);

create table floor_configuration (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    floor_name varchar(120) not null,
    room_type_name varchar(120) not null,
    room_count integer,
    start_number integer,
    constraint fk_floor_config_property foreign key (property_id) references property(id)
);

create table inventory_room (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    floor_name varchar(120) not null,
    room_type_name varchar(120) not null,
    room_number varchar(30) not null,
    constraint uk_inventory_room_number unique (property_id, room_number),
    constraint fk_inventory_room_property foreign key (property_id) references property(id),
    constraint ck_inventory_room_number_not_blank check (length(trim(room_number)) > 0)
);

create table property_area (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    area_name varchar(150) not null,
    quantity integer not null,
    maximum_capacity integer not null,
    description varchar(1000),
    amenities_csv varchar(2000),
    images_csv varchar(4000),
    constraint fk_property_area_property foreign key (property_id) references property(id)
);

create table room_outlet_type (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    room_name varchar(150) not null,
    room_code varchar(80),
    quantity integer not null,
    available_for_sell boolean not null,
    maximum_guest_occupancy integer not null,
    description varchar(1000),
    amenities_csv varchar(2000),
    images_csv varchar(4000),
    constraint fk_room_outlet_type_property foreign key (property_id) references property(id)
);

create unique index uq_room_outlet_type_property_room_code on room_outlet_type(property_id, room_code)
    where room_code is not null;

create table floor_property_area (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    floor_name varchar(120) not null,
    area_name varchar(150) not null,
    quantity integer not null,
    constraint fk_floor_property_area_property foreign key (property_id) references property(id)
);

create table chart_of_account (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    account_code varchar(80) not null,
    account_name varchar(150) not null,
    account_type varchar(80) not null,
    ledger_type varchar(80) not null,
    active boolean not null,
    constraint fk_chart_of_account_property foreign key (property_id) references property(id)
);

create table revenue_mapping (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    charge_type varchar(120) not null,
    map_gl_account varchar(80) not null,
    status varchar(40) not null,
    description varchar(255),
    constraint fk_revenue_mapping_property foreign key (property_id) references property(id)
);

create table payment_method (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    payment_method varchar(80) not null,
    account_mapping varchar(80) not null,
    allow_refund boolean not null,
    active boolean not null,
    constraint fk_payment_method_property foreign key (property_id) references property(id)
);

create table tax_rule (
    id bigint generated by default as identity primary key,
    property_id varchar(36) not null,
    tax_name varchar(120) not null,
    type varchar(40) not null,
    applicable_on varchar(40) not null,
    rate double precision not null,
    active boolean not null,
    priority integer not null,
    incl_excl varchar(20) not null,
    effective_date varchar(40) not null,
    status varchar(40) not null,
    constraint fk_tax_rule_property foreign key (property_id) references property(id)
);

create index idx_property_draft_status on property_draft(status);
create index idx_property_city on property(city);
create index idx_room_type_property on room_type(property_id);
create index idx_floor_property on floor_configuration(property_id);
create index idx_inventory_property on inventory_room(property_id);
create index idx_coa_property on chart_of_account(property_id);
create index idx_revenue_mapping_property on revenue_mapping(property_id);
create index idx_payment_method_property on payment_method(property_id);
create index idx_tax_rule_property on tax_rule(property_id);
create index idx_guest_service_amenity_property on guest_service_amenity(property_id);
create index idx_nearby_location_accessibility_property on nearby_location_accessibility(property_id);
create index idx_property_area_property on property_area(property_id);
create index idx_room_outlet_type_property on room_outlet_type(property_id);
create index idx_floor_property_area_property on floor_property_area(property_id);
create index idx_floor_property_area_floor on floor_property_area(property_id, floor_name);



